### ISSUE TITLE
Add Issue Templates for `EPIC` and `USER STORY`

### ISSUE THREAD

**Issue by lechitz** [lechitz/AionApi#90]
## **General Information**
- **Category:** `docs`
- **Priority:** Medium

---

## **Description**

This issue aims to add two new standardized issue templates to the AionAPI project:

- `EPIC` template → Used to group related features or user stories under a common goal or architectural module.
- `User Story` template → Used to define small, functional tasks from the perspective of the user, with clear acceptance criteria and execution scope.

These templates will professionalize issue tracking, improve planning visibility, and enable the project board to be structured around a scalable product roadmap.

---

## **Acceptance Criteria**
- [x] A file named `epic.yml` is created under `.github/ISSUE_TEMPLATE/`
- [x] A file named `user-story.yml` is created under `.github/ISSUE_TEMPLATE/`
- [x] Both templates contain:
  - Title, description, labels, and assignment section
  - Fields for priority, acceptance criteria, execution plan, impacts, and related links
- [x] Templates follow AionAPI documentation standards
- [ ] Templates appear in the GitHub “New Issue” interface

---

#### `.github/ISSUE_TEMPLATE/epic.yml`

```yaml

## General Information
- **Category:** `epic`
- **Priority:** *(Low / Medium / High / Critical)*

---

## Description
Describe the scope of this epic, including:
- The overall goal and purpose.
- Modules or features it will cover.
- How it aligns with product or architectural goals.
- Expected benefits and long-term value.

---

## Impact
List positive impacts and high-level considerations:
- Project modularity, scalability, technical debt resolution, etc.

---

## Supplementary Materials
Add any related documents or references:
- [Architecture Guide](#)
- [Design Docs](#)
- [Tracking Board View](#)
```

---

#### `.github/ISSUE_TEMPLATE/user-story.yml`

```yaml

## General Information
- **Priority:** *(Low / Medium / High / Critical)*
- **Status:** *(To Do / In Progress / In Review / Done)*

---

## Description
Describe the background and goal of this functionality. Include:
- The scope of the work.
- Any business logic or rules involved.
- Dependencies or integration with other modules.

---

## Acceptance Criteria
- [ ] The functionality meets the needs described in the story.
- [ ] Tests are implemented and pass successfully.
- [ ] Documentation is created or updated.
- [ ] Reviewed and approved by project maintainers.

---

## Execution Plan
Explain the development approach:
- Which modules/services will be involved.
- Whether it touches core, ports, adapters, etc.
- Any key decisions or validations required.

---

## Impacts
Describe the benefits and any side effects or considerations:
- System behavior, new flows, future refactors, etc.

---

## Supplementary Materials
Include any helpful links or design references:
- [Use Case Specification](#)
- [Mockups or API Samples](#)
- [Related Issues](#)
```
